workspace:
  base: /dist
  path: .
pipeline:
  build:
    image: node:10
    commands:
      - cd backend/src
      - npm install
      - npm run build
      - pwd
  rsync:
      image: drillster/drone-rsync
      user: ${rsync_user}
      key: ${rsync_key}
      hosts:
        - 35.201.251.211
      source: ./dist/backend/src
      target: ~/github
      script:
        - pwd
