
pipeline:
  build:
    image: node:10
    commands:
      - cd backend/src
      - npm install
      - npm run build
      - pwd
  rsync:
    image: drillster/drone-rsync
    user: root
    key: ${RSYNC_KEY}
    hosts:
      - 35.201.251.211
    source: .
    target: /home/jinwyp/github
    script:
      - pwd
      - echo key ${RSYNC_KEY}
    secrets: [ RSYNC_KEY ]
